### ISSUE TITLE
Make the client standalone

### ISSUE THREAD

**Issue by futuretonight** [TheGrandCurator/Cheddar-BratWurst7#75]
As we see wurst uses fabric api and loader to just run the client and it's painful if you maintain every version of wurst so just in 1 click we get the client without depending on other APIs and stuff

**Comment by TheGrandCurator** [comment]
I'm not sure I understand. Are you asking to not have to use fabric loader?

**Comment by futuretonight** [comment]
Yes it can be ran like how the salwyrr client is it use nothing just a file run it and you get a whole new client

**Comment by TheGrandCurator** [comment]
No.
